import = ["~/.config/alacritty/themes/themes/monokai_charcoal.yaml"]

[env]
TERM = "xterm-256color"

[font]
size = 8

[font.bold]
family = "Hack NFM"
style = "Bold"

[font.bold_italic]
family = "Hack NFM"
style = "Bold Italic"

[font.italic]
family = "Hack NFM"
style = "Italic"

[font.normal]
family = "Hack NFM"
style = "Regular"
