import = ["~/.config/alacritty/themes/themes/monokai_charcoal.yaml"]

[env]
TERM = "xterm-256color"

[window]
opacity=0.95
padding={x=10,y=10}

[font]
size = 9

[font.bold]
family = "Hack NFM"
style = "Bold"

[font.bold_italic]
family = "Hack NFM"
style = "Bold Italic"

[font.italic]
family = "Hack NFM"
style = "Italic"

[font.normal]
family = "Hack NFM"
style = "Regular"
