mode = "dark"

accent = "#d83a3a"
selection = "#28303d"
muted = "#556377"

background = "#13161c"
dark_background = "#0d0f13"
darker_background = "#08090c"
lighter_background = "#1c212a"

foreground = "#d8e1e8"
dark_foreground = "#69798c"
light_foreground = "#b4c3d2"
bright_foreground = "#f0f5f9"

red = "#d83a3a"
yellow = "#deb859"
orange = "#e07a48"
green = "#6da87b"
cyan = "#78b8c4"
blue = "#5e8aa6"
magenta = "#a66885"
brown = "#5a453e"

bright_red = "#e84e4e"
bright_yellow = "#e8c973"
bright_green = "#82bd90"
bright_cyan = "#92cdd7"
bright_blue = "#7da8c3"
bright_magenta = "#ba7b99"
