mode = "dark"

accent = "#8ace00"
selection = "#243314"
muted = "#4a5d35"

background = "#0e1309"
dark_background = "#090d06"
darker_background = "#050703"
lighter_background = "#192212"

foreground = "#f0f6e8"
dark_foreground = "#6b8252"
light_foreground = "#cce2a8"
bright_foreground = "#ffffff"

hyprland_active_border = "rgba(8ace00ee) rgba(b5ff1cee) 45deg"
hyprland_inactive_border = "rgba(1f2b12aa)"

red = "#ff4d6d"
yellow = "#d4eb1a"
orange = "#ff8c38"
green = "#8ace00"
cyan = "#34e8ba"
blue = "#4ea2ff"
magenta = "#d957ff"
brown = "#6b5830"

bright_red = "#ff6b85"
bright_yellow = "#e2ff2b"
bright_green = "#a4ff1a"
bright_cyan = "#6bfce2"
bright_blue = "#78b8ff"
bright_magenta = "#e67dff"
